# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acaac28a6f8d31638c321e904c79cbfcf11e2341b648a99f7e6fad7f0aa6d3c8b63bd78ce3d9e56949956e9aedfe40e8af79f441f026c58c806121e5641ac814

test:
  secret_key_base: 39d8727a4190b79021c0ef2569ede6a13daf6567321a0b276bfaeb4c97d0391590a0834c8f18de308cb6e2a08801148414eb09672497b5f3f87b84e7ac320479

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
